from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status, Query
from psycopg import Connection
from psycopg.rows import dict_row
from server.app.core.database import get_db
from server.app.core.dependencies import require_roles, get_current_user
from server.app.schemas import AssetCreate, AssetResponse

router = APIRouter(prefix="/assets", tags=["Assets"])

@router.get("", response_model=List[AssetResponse])
def get_assets(
    search: Optional[str] = Query(None, description="Search by name, tag, or serial number"),
    category: Optional[int] = Query(None, description="Filter by category ID"),
    status_filter: Optional[str] = Query(None, alias="status", description="Filter by status"),
    department: Optional[int] = Query(None, description="Filter by active holder's department ID"),
    bookable: Optional[bool] = Query(None, description="Filter by bookable status"),
    page: int = Query(1, ge=1, description="Page number"),
    current_user: dict = Depends(get_current_user),
    db: Connection = Depends(get_db)
):
    """
    Retrieve assets with advanced search, filters, and pagination.
    Includes active holder information.
    """
    limit = 20
    offset = (page - 1) * limit

    base_query = """
        SELECT 
            a.id, 
            a.tag, 
            a.name, 
            a.serial_number, 
            a.category_id, 
            a.cost, 
            a.acquisition_date, 
            a.condition, 
            a.location, 
            a.photo_url, 
            a.is_bookable, 
            a.status, 
            a.created_at,
            c.name AS category_name,
            COALESCE(u.name, dept.name) AS current_holder_name,
            CASE 
                WHEN alloc.employee_id IS NOT NULL THEN 'employee'
                WHEN alloc.department_id IS NOT NULL THEN 'department'
                ELSE NULL
            END AS current_holder_type
        FROM assets a
        LEFT JOIN categories c ON a.category_id = c.id
        LEFT JOIN allocations alloc ON a.id = alloc.asset_id AND alloc.returned_at IS NULL
        LEFT JOIN users u ON alloc.employee_id = u.id
        LEFT JOIN departments dept ON alloc.department_id = dept.id
        WHERE 1=1
    """
    params = []

    if search:
        base_query += " AND (a.name ILIKE %s OR a.tag ILIKE %s OR a.serial_number ILIKE %s)"
        search_pattern = f"%{search}%"
        params.extend([search_pattern, search_pattern, search_pattern])

    if category is not None:
        base_query += " AND a.category_id = %s"
        params.append(category)

    if status_filter:
        base_query += " AND a.status = %s"
        params.append(status_filter)

    if department is not None:
        base_query += " AND COALESCE(alloc.department_id, u.department_id) = %s"
        params.append(department)

    if bookable is not None:
        base_query += " AND a.is_bookable = %s"
        params.append(bookable)

    base_query += " ORDER BY a.tag ASC LIMIT %s OFFSET %s"
    params.extend([limit, offset])

    with db.cursor() as cur:
        cur.execute(base_query, params)
        return cur.fetchall()

@router.post("", response_model=AssetResponse, status_code=status.HTTP_201_CREATED)
def create_asset(
    asset_in: AssetCreate,
    current_user: dict = Depends(require_roles("admin", "asset_manager")),
    db: Connection = Depends(get_db)
):
    """
    Register a new asset. Tag is auto-generated by the database sequence.
    (Admin and Asset Manager only).
    """
    try:
        with db.cursor() as cur:
            # Insert the new asset (let default sequence generate tag)
            cur.execute(
                """
                INSERT INTO assets (
                    name, serial_number, category_id, cost, 
                    acquisition_date, condition, location, photo_url, is_bookable
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id, tag, name, serial_number, category_id, cost, 
                          acquisition_date, condition, location, photo_url, 
                          is_bookable, status, created_at
                """,
                (
                    asset_in.name, asset_in.serial_number, asset_in.category_id,
                    asset_in.cost, asset_in.acquisition_date, asset_in.condition.value,
                    asset_in.location, asset_in.photo_url, asset_in.is_bookable
                )
            )
            asset = cur.fetchone()
            
            # Log history event
            cur.execute(
                """
                INSERT INTO asset_history (asset_id, event_type, detail, actor_id)
                VALUES (%s, 'registered', %s, %s)
                """,
                (asset["id"], f"Asset registered: {asset['name']} ({asset['tag']})", current_user["id"])
            )
            
            db.commit()
            
            # Fetch response with category name
            cur.execute(
                """
                SELECT a.*, c.name AS category_name
                FROM assets a
                LEFT JOIN categories c ON a.category_id = c.id
                WHERE a.id = %s
                """,
                (asset["id"],)
            )
            return cur.fetchone()
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to register asset: {str(e)}"
        )

@router.get("/{id}")
def get_asset_detail(
    id: int,
    current_user: dict = Depends(get_current_user),
    db: Connection = Depends(get_db)
):
    """
    Get detailed information for a specific asset, including its complete
    allocation and maintenance event history.
    """
    with db.cursor() as cur:
        # Get asset core info
        cur.execute(
            """
            SELECT 
                a.id, 
                a.tag, 
                a.name, 
                a.serial_number, 
                a.category_id, 
                a.cost, 
                a.acquisition_date, 
                a.condition, 
                a.location, 
                a.photo_url, 
                a.is_bookable, 
                a.status, 
                a.created_at,
                c.name AS category_name,
                COALESCE(u.name, dept.name) AS current_holder_name,
                CASE 
                    WHEN alloc.employee_id IS NOT NULL THEN 'employee'
                    WHEN alloc.department_id IS NOT NULL THEN 'department'
                    ELSE NULL
                END AS current_holder_type
            FROM assets a
            LEFT JOIN categories c ON a.category_id = c.id
            LEFT JOIN allocations alloc ON a.id = alloc.asset_id AND alloc.returned_at IS NULL
            LEFT JOIN users u ON alloc.employee_id = u.id
            LEFT JOIN departments dept ON alloc.department_id = dept.id
            WHERE a.id = %s
            """,
            (id,)
        )
        asset = cur.fetchone()
        if not asset:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Asset with ID {id} not found."
            )

        # Get history logs
        cur.execute(
            """
            SELECT 
                h.id,
                h.event_type,
                h.detail,
                h.created_at,
                u.name AS actor_name
            FROM asset_history h
            LEFT JOIN users u ON h.actor_id = u.id
            WHERE h.asset_id = %s
            ORDER BY h.created_at DESC
            """,
            (id,)
        )
        history = cur.fetchall()
        
        # Add history list to the response body
        response_data = dict(asset)
        response_data["history"] = history
        return response_data
